version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: npm
    directory: /download
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: docker
    directory: /download
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
